export interface MarvelEntry {
  id: string;
  title: string;
}

export interface MarvelUniverse {
  id: string;
  label: string;
  color: string;
  entries: MarvelEntry[];
}

export const UNIVERSES: MarvelUniverse[] = [
  {
    id: "earth-96283",
    label: "Earth-96283",
    color: "#e63946",
    entries: [
      { id: "96283-1", title: "Spider-Man [2002]" },
      { id: "96283-2", title: "Spider-Man 2" },
      { id: "96283-3", title: "Spider-Man 3" },
    ],
  },
  {
    id: "earth-120703",
    label: "Earth-120703",
    color: "#f4a261",
    entries: [
      { id: "120703-1", title: "The Amazing Spider-Man" },
      { id: "120703-2", title: "The Amazing Spider-Man 2" },
    ],
  },
  {
    id: "mcu-1",
    label: "Earth-199999 / MCU [Part 1]",
    color: "#e9c46a",
    entries: [
      { id: "mcu-1-1", title: "Eyes of Wakanda" },
      { id: "mcu-1-2", title: "Captain America: The First Avenger" },
      { id: "mcu-1-3", title: "One-Shot: Agent Carter" },
      { id: "mcu-1-4", title: "Captain Marvel" },
      { id: "mcu-1-5", title: "Iron Man" },
      { id: "mcu-1-6", title: "Iron Man 2" },
      { id: "mcu-1-7", title: "The Incredible Hulk" },
      { id: "mcu-1-8", title: "One-Shot: A Funny Thing Happened on the Way to Thor's Hammer" },
      { id: "mcu-1-9", title: "Thor" },
      { id: "mcu-1-10", title: "One-Shot: The Consultant" },
      { id: "mcu-1-11", title: "The Avengers" },
      { id: "mcu-1-12", title: "One-Shot: Item 47" },
      { id: "mcu-1-13", title: "Iron Man 3" },
      { id: "mcu-1-14", title: "One-Shot: All Hail the King" },
      { id: "mcu-1-15", title: "Agent Carter Season 1" },
      { id: "mcu-1-16", title: "Thor: The Dark World" },
      { id: "mcu-1-17", title: "Captain America: The Winter Soldier" },
      { id: "mcu-1-18", title: "Guardians of the Galaxy" },
      { id: "mcu-1-19", title: "I am Groot Season 1, Episode 1" },
      { id: "mcu-1-20", title: "Guardians of the Galaxy Vol. 2" },
      { id: "mcu-1-21", title: "I am Groot Season 1, Episode 2-5" },
      { id: "mcu-1-22", title: "I am Groot Season 2" },
      { id: "mcu-1-23", title: "Daredevil Season 1" },
      { id: "mcu-1-24", title: "Agent Carter Season 2" },
      { id: "mcu-1-25", title: "Jessica Jones Season 1" },
      { id: "mcu-1-26", title: "Avengers: Age of Ultron" },
      { id: "mcu-1-27", title: "WHIH Newsfront Season 1" },
      { id: "mcu-1-28", title: "Ant-Man" },
      { id: "mcu-1-29", title: "Daredevil Season 2" },
      { id: "mcu-1-30", title: "Luke Cage Season 1" },
      { id: "mcu-1-31", title: "Iron Fist Season 1" },
      { id: "mcu-1-32", title: "The Defenders" },
      { id: "mcu-1-33", title: "WHIH Newsfront Season 2" },
      { id: "mcu-1-34", title: "Captain America: Civil War" },
      { id: "mcu-1-35", title: "Black Widow" },
      { id: "mcu-1-36", title: "Black Panther" },
      { id: "mcu-1-37", title: "Spider-Man: Homecoming" },
      { id: "mcu-1-38", title: "The Punisher Season 1" },
      { id: "mcu-1-39", title: "Doctor Strange" },
      { id: "mcu-1-40", title: "Jessica Jones Season 2" },
      { id: "mcu-1-41", title: "Luke Cage Season 2" },
      { id: "mcu-1-42", title: "Thor: Ragnarok" },
      { id: "mcu-1-43", title: "Iron Fist Season 2" },
      { id: "mcu-1-44", title: "Daredevil Season 3" },
      { id: "mcu-1-45", title: "The Punisher Season 2" },
      { id: "mcu-1-46", title: "Jessica Jones Season 3" },
      { id: "mcu-1-47", title: "Ant-Man and the Wasp" },
      { id: "mcu-1-48", title: "Avengers: Infinity War" },
      { id: "mcu-1-49", title: "Avengers: Endgame" },
      { id: "mcu-1-50", title: "Loki" },
      { id: "mcu-1-51", title: "What if…? Season 1" },
      { id: "mcu-1-52", title: "WandaVision" },
      { id: "mcu-1-53", title: "Eternals" },
      { id: "mcu-1-54", title: "Shang-Chi and the Legend of the Ten Rings" },
      { id: "mcu-1-55", title: "What if…? Season 2" },
      { id: "mcu-1-56", title: "The Falcon and the Winter Soldier" },
      { id: "mcu-1-57", title: "Peter's To-Do List" },
      { id: "mcu-1-58", title: "Spider-Man: Far From Home" },
      { id: "mcu-1-59", title: "The Daily Bugle Season 1" },
      { id: "mcu-1-60", title: "Spider-Man: No Way Home" },
      { id: "mcu-1-61", title: "The Daily Bugle Season 2" },
      { id: "mcu-1-62", title: "Doctor Strange in the Multiverse of Madness" },
      { id: "mcu-1-63", title: "Hawkeye" },
      { id: "mcu-1-64", title: "Moon Knight" },
      { id: "mcu-1-65", title: "Thor: Love and Thunder" },
      { id: "mcu-1-66", title: "Black Panther: Wakanda Forever" },
      { id: "mcu-1-67", title: "What if…? Season 3" },
      { id: "mcu-1-68", title: "Echo" },
      { id: "mcu-1-69", title: "She-Hulk: Attorney at Law" },
      { id: "mcu-1-70", title: "Ms. Marvel" },
      { id: "mcu-1-71", title: "Marvel Zombies" },
      { id: "mcu-1-72", title: "Ironheart" },
      { id: "mcu-1-73", title: "Werewolf by Night" },
      { id: "mcu-1-74", title: "The Guardians of the Galaxy Holiday Special" },
      { id: "mcu-1-75", title: "Ant-Man and the Wasp: Quantumania" },
      { id: "mcu-1-76", title: "Guardians of the Galaxy Vol. 3" },
      { id: "mcu-1-77", title: "Secret Invasion" },
      { id: "mcu-1-78", title: "The Marvels" },
      { id: "mcu-1-79", title: "Loki Season 2" },
      { id: "mcu-1-80", title: "Agatha All Along" },
      { id: "mcu-1-81", title: "Daredevil: Born Again Season 1" },
      { id: "mcu-1-82", title: "Captain America: Brave New World" },
      { id: "mcu-1-83", title: "Thunderbolts*" },
      { id: "mcu-1-84", title: "Daredevil: Born Again Season 2" },
      { id: "mcu-1-85", title: "Wonder Man" },
      { id: "mcu-1-86", title: "The Punisher: One Last Kill" },
      { id: "mcu-1-87", title: "Spider-Man: Brand New Day" },
      { id: "mcu-1-88", title: "VisionQuest" },
    ],
  },
  {
    id: "earth-688",
    label: "Earth-688 / SSU",
    color: "#2a9d8f",
    entries: [
      { id: "688-1", title: "Madame Web" },
      { id: "688-2", title: "Venom" },
      { id: "688-3", title: "Morbius" },
      { id: "688-4", title: "The Daily Bugle Season 3" },
      { id: "688-5", title: "Venom: Let There Be Carnage" },
      { id: "688-6", title: "Venom: The Last Dance" },
      { id: "688-7", title: "Kraven the Hunter" },
    ],
  },
  {
    id: "earth-121698",
    label: "Earth-121698",
    color: "#457b9d",
    entries: [
      { id: "121698-1", title: "Fantastic Four [2005]" },
      { id: "121698-2", title: "Fantastic Four: Rise of the Silver Surfer" },
    ],
  },
  {
    id: "earth-701306",
    label: "Earth-701306",
    color: "#6d6875",
    entries: [
      { id: "701306-1", title: "Daredevil [2003]" },
      { id: "701306-2", title: "Elektra" },
    ],
  },
  {
    id: "earth-26320",
    label: "Earth-26320",
    color: "#b5838d",
    entries: [
      { id: "26320-1", title: "Blade" },
      { id: "26320-2", title: "Blade II" },
      { id: "26320-3", title: "Blade: Trinity" },
      { id: "26320-4", title: "Blade: The Series" },
    ],
  },
  {
    id: "earth-10005",
    label: "Earth-10005",
    color: "#f77f00",
    entries: [
      { id: "10005-1", title: "X-Men: First Class" },
      { id: "10005-2", title: "X-Men Origins: Wolverine" },
      { id: "10005-3", title: "X-Men" },
      { id: "10005-4", title: "X2" },
      { id: "10005-5", title: "X-Men: The Last Stand" },
      { id: "10005-6", title: "The Wolverine" },
      { id: "10005-7", title: "X-Men: Days of Future Past" },
      { id: "10005-8", title: "X-Men: Apocalypse" },
      { id: "10005-9", title: "X-Men: Dark Phoenix" },
      { id: "10005-10", title: "Deadpool" },
      { id: "10005-11", title: "No Good Deed" },
      { id: "10005-12", title: "The New Mutants" },
      { id: "10005-13", title: "Deadpool 2" },
      { id: "10005-14", title: "Logan" },
      { id: "10005-15", title: "Deadpool & Wolverine" },
    ],
  },
  {
    id: "earth-828",
    label: "Earth-828",
    color: "#4cc9f0",
    entries: [
      { id: "828-1", title: "The Fantastic Four: First Steps" },
    ],
  },
  {
    id: "mcu-2",
    label: "Earth-199999 / MCU [Part 2]",
    color: "#e9c46a",
    entries: [
      { id: "mcu-2-1", title: "Avengers: Doomsday" },
      { id: "mcu-2-2", title: "Daredevil: Born Again Season 3" },
      { id: "mcu-2-3", title: "Avengers: Secret Wars" },
    ],
  },
  {
    id: "earth-67",
    label: "Earth-67 / 6799",
    color: "#ff6b6b",
    entries: [
      { id: "67-1", title: "Spider-Man [1967]" },
    ],
  },
  {
    id: "earth-26496",
    label: "Earth-26496",
    color: "#ffd166",
    entries: [
      { id: "26496-1", title: "Spectacular Spider-Man" },
    ],
  },
  {
    id: "earth-751263",
    label: "Earth-751263",
    color: "#06d6a0",
    entries: [
      { id: "751263-1", title: "Spider-Man Unlimited" },
    ],
  },
  {
    id: "spider-verse",
    label: "Spider-Verse",
    color: "#c77dff",
    entries: [
      { id: "sv-1", title: "Spider-Ham: Caught in a Ham" },
      { id: "sv-2", title: "Spider-Man: Into the Spider-Verse" },
      { id: "sv-3", title: "THE SPIDER WITHIN: A SPIDER-VERSE STORY" },
      { id: "sv-4", title: "Spider-Man: Across the Spider-Verse" },
      { id: "sv-5", title: "Spider-Man: Beyond the Spider-Verse" },
    ],
  },
];